blank_issues_enabled: false
contact_links:
  - name: OctoTask related issues
    url: https://github.com/octotask/octotask/issues/new/choose
    about: Report issues related to OctoTask
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other octotask users.
